clc
clear

addpath('./Fmp2');
addpath('./simulation');
addpath('./chiTest');
addpath('./operation');

dataFolder = '../data/tidy/ACS_13_5YR_DP03/aggregate';
files = dir(fullfile(dataFolder, '*.noanno.csv'));

for( i = 1:length(files))
    data.(strrep(strrep(files(i).name,'.noanno.csv',''),' ','')) = csvread(strcat(dataFolder,'/',files(i).name));
end

clc
flds = fieldnames(data);
for( iState = 1:length(flds) )
    [ est.(flds{iState}).mu,...
        est.(flds{iState}).s,...
        est.(flds{iState}).a,...
        est.(flds{iState}).a0,...
        est.(flds{iState}).aj0,...
        est.(flds{iState}).p ] = Fmp2MMEst( data.(flds{iState}), 'Kendall' );

F.(flds{iState}) = Fmp2( est.(flds{iState}).a0, est.(flds{iState}).a, est.(flds{iState}).s, est.(flds{iState}).mu );
[ Chi.(flds{iState}),...
    pVal.(flds{iState}),...
    nObs.(flds{iState}),...
    O.(flds{iState}),...
    E.(flds{iState}),...
    bins.(flds{iState}) ] = chiTest( data.(flds{iState}), F.(flds{iState}),...
    10, false,...
    @(x) fprintf('Procces: %s\n', strtrim(rats(x))));
end
%%
